name: Label Bug Pull Requests

on: 
  pull_request:
    types: [opened]
    branches:
      - '**/fix/**'
      - '**/bug/**'
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "fix"
