name: Label Pull Requests

on: [pull_request]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "feature"
