on:
  pull_request:
    branches:
      - '**/feat/**'
      - '**/feature/**'
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "feature"
