name: Label Feature Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    name: Label pull requests
    steps:
      - uses: actions/checkout@v2
      - uses: IvanFon/super-labeler-action@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
