name: Release Notification
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  send_message:
    uses: slackapi/slack-github-action@v1.23.0
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
     with:
        text: A release is published.
        blocks: |
          [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "${{ github.event.release.tag_name}} is published!"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Author:*\n${{ github.actor }}"
              }
            },
              {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Information:*"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": ${{ toJSON(github.event.release.body) }}
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "${{ github.event.release.html_url }}"
              }
            }
          ]

