name: Release Notification

on:
  release:
    types: [published]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clean release notes
        run: python .github/workflows/clean_release_notes.py ${{toJSON(github.event.release.body)}}

      - name: Send notification
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_NOTIFICATION_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "A release has been published!",
              "blocks": [
                 {
                   "type": "header",
                   "text": {
                     "type": "plain_text",
                     "text": "${{ github.event.release.tag_name}} has been published!"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "*Author:* ${{ github.actor }}"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "${{ env.RELEASE_NOTES }}"
                   }
                 }
              ]
            }

