name: Release Notification

on:
  release:
    types: [published]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_NOTIFICATION_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "A release has been published!",
              "blocks": [
                 {
                   "type": "header",
                   "text": {
                     "type": "plain_text",
                     "text": "${{ github.event.release.tag_name}} is published!"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "*Author:*\n${{ github.actor }}"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "*Information (raw):*"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "${{ github.event.release.body }}"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "*Information (toJSON):*"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": ${{ toJSON(github.event.release.body) }}
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "${{ github.event.release.html_url }}"
                   }
                 }
              ]
            }

